backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Main_image, name: main_image, widget: image}
          - {label: About_me_image, name: about_me_image, widget: image}
          - {label: Redirects_image, name: redirects_image, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: Photo_tiles, name: photo_tiles, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Tiles, name: tiles, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Show_title, name: show_title, widget: text}, {label: Role, name: role, widget: text}]}]}
      - file: "src/pages/resume/index.md"
        label: "Resume Page"
        name: "resume"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "resume-page"}
          - {label: Resume_image, name: resume_image, widget: image}
          - {label: Headshot_image, name: headshot_image, widget: image}
          - {label: "Resume_PDF", name: "resume_pdf", widget: "file"}
      - file: "src/pages/gallery/index.md"
        label: "Photo Gallery Page"
        name: "gallery"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "gallery-page"}
          - {label: Headshots, name: headshots, widget: list, fields: [{label: Image, name: image, widget: image}]}
          - {label: Shows, name: shows, widget: list, fields: [{label: Title, name: title, widget: string}, {label: Theater, name: theater, widget: string}, {label: Photos, name: photos, widget: list, fields: [{label: Height, name: height, widget: number}, {label: Cool, name: cool, widget: number}, {label: Width, name: width, widget: number}, {label: src, name: src, widget: image}, {label: Caption, name: caption, widget: text} ]}]}
      - file: "src/pages/media/index.md"
        label: "Media Page"
        name: "media"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "media-page"}
          - {label: Videos, name: videos, widget: list, fields: [{label: Video, name: video, widget: string}]}
          - {label: Press, name: press, widget: list, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: Link, name: link, widget: string}]}