backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Main_image, name: main_image, widget: image}
          - {label: About_me_image, name: about_me_image, widget: image}
          - {label: Redirects_image, name: redirects_image, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: Photo_tiles, name: photo_tiles, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Tiles, name: tiles, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Show_title, name: show_title, widget: text}, {label: Role, name: role, widget: text}]}]}
          # - {label: Heading, name: heading, widget: string}
          # - {label: Aboutme, name: aboutme, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          # - {label: Description, name: description, widget: string}
          # - {label: Photo_tiles, name: photo_tiles, widget: object, fields: [{label: Show_title, name: show_title, widget: string}, {label: Role, name: role, widget: string}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/resume/index.md"
        label: "Resume Page"
        name: "resume"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "resume-page"}
          - {label: Resume_image, name: resume_image, widget: image}
          - {label: Headshot_image, name: headshot_image, widget: image}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "src/pages/gallery/index.md"
        label: "Photo Gallery Page"
        name: "gallery"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "gallery-page"}
          - {label: Headshots, name: headshots, widget: list, fields: [{label: Image, name: image, widget: image}]}
          - {label: Shows, name: shows, widget: list, fields: [{label: Title, name: title, widget: string}, {label: Theater, name: theater, widget: string}, {label: Photos, name: photos, widget: list, fields: [{label: src, name: src, widget: image}, {label: Text, name: text, widget: text}, {label: Width, name: width, widget: text}, {label: Height, name: height, widget: text}]}]}
      - file: "src/pages/media/index.md"
        label: "Media Page"
        name: "media"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "media-page"}
          - {label: Videos, name: videos, widget: list, fields: [{label: Video, name: video, widget: string}]}
          - {label: Press, name: press, widget: list, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: Link, name: link, widget: string}]}